from typing import Dict, Any
from src.graph.state import AgentState
from src.utils.record_sorter import sort_record_by_codebook, translate_to_codebook_headers

class SynthesisAgent:
    """
    Consolidates payloads generated by concurrent extraction workers,
    flattening separate sub-schemas into an aggregated database record.
    """
    def __call__(self, state: AgentState) -> Dict[str, Any]:
        print("🧠 [SynthesisAgent] Merging extracted feature-sets into master record...")
        
        # Pull the list of accumulated outputs from state
        feature_list = state.get("extracted_features", [])
        
        # Create a single flat dictionary to house all codebook fields
        records = {}
        
        # Iterate through the updates deposited by the upstream nodes
        for feature in feature_list:
            agent_name = feature.get("agent_name")
            data_payload = feature.get("data", {})
            
            print(f"       -> Compiling features from: {agent_name}")
            # Dynamic dictionary merge
            records.update(data_payload)

        ordered_records = sort_record_by_codebook(records)
        translated_records = translate_to_codebook_headers(ordered_records)
            
        # Place the beautifully aggregated flat dictionary into a final state key
        return {
            "final_consolidated_record": ordered_records,
            "translated_cookbook_record": translated_records
        }

# Instantiate the node instance referenced by the workflow file
synthesis_node = SynthesisAgent()
